version: "3.8"
services:
  mosquitto:
    image: 'eclipse-mosquitto'
    container_name: 'mosquitto'
    volumes:
      - type: bind
        source: './mosquitto/configuration/'
        target: '/mosquitto/config/'
      - type: bind
        source: './mosquitto/data'
        target: '/mosquitto/data'
      - type: bind
        source: './mosquitto/logs'
        target: '/mosquitto/log'
    env_file:
      - ./mosquitto/.env
    ports:
      - "1883:1883"
      - "9001:9001"
      - "1884:1884"
  influxdb:
    image: 'influxdb'
    container_name: 'influxdb'
    volumes:
      - type: volume
        source: influxData
        target: '/var/lib/influxdb2'
    ports:
      - "8086:8086"
    env_file:
      - './influxdb/.env'
  server:
    build: "./server/"
    container_name: server
    volumes:
      - type: bind
        source: './server'
        target: '/app'
    depends_on:
      - mosquitto
      - influxdb
volumes:
  influxData:
